### ISSUE TITLE
to-do list for Builder v1.00

### ISSUE THREAD

**Issue by haseebeqx** [haseebeqx/tsrecord#3]
- [ ] joins  -assigned to @haseebeqx
- [ ] distinct
- [ ] max
- [ ] union
- [ ] making a interface for unique data returned on all sql inserts.
- [x] npm compatibility
- [ ] advanced groupby
- [ ] skip and take
- [ ] transactions
### in `` Database`` class
- [ ] create table
- [ ] delete table
- [ ] change database connection params dynamically 
- [ ] direct sql query - assigned to @haseebeqx
